apiVersion: apps/v1
kind: Deployment
metadata:
  name: comic-colorizer-backend
spec:
  selector:
    matchLabels:
      app: comic-colorizer-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: comic-colorizer-backend
    spec:
      containers:
        - name: comic-colorizer-backend
          image: asia-southeast1-docker.pkg.dev/comvis-ict-2021/comic-colorizer/comic-colorizer-backend:v5-release
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "2"
              memory: "4Gi"
      restartPolicy: Always
